spin_manifest_version = 2

[application]
name = "Go Azure"
# Update with latest version number (semver)
version = "0.1.0"
authors = ["Fermyon Engineering Team <engineering@fermyon.com>"]

[[trigger.http]]
route = "/..."
component = "go-azure"

[component.go-azure]
source = "main.wasm"

[component.go-azure.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]