name: Build and Push Azure Client Package
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     

      - name: set the release version
        run: echo "RELEASE_VERSION=$(yq '.application.version' spin.toml)" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: setup spin
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ github.token }}

      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"

      - name: install tinygo
        uses: rajatjindal/setup-actions/tinygo@v0.0.1
        with:
          version: "v0.32.0"

      - name: install wkg
        run: cargo install --git https://github.com/bytecodealliance/wasm-pkg-tools wkg --locked --config net.git-fetch-with-cli=true

      
      - name: cache the wkg installation for the next time this runs
        uses: Swatinem/rust-cache@v2
      
      - name: build spinapp
        run: spin build
      
      - name: login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push package
        run: wkg oci push ghcr.io/fermyon/wasm-pkg/fermyon-experimental/azure-client:${{ env.RELEASE_VERSION }} main.wasm